### ISSUE TITLE
deniteのキーマップ変更をスムーズに反映させたい

### ISSUE THREAD

**Issue by mikanIchinose** [mikanIchinose/neovim-sandbox#1]
## ASIS
`[plugins.ftplugin]` で設定しているdeniteバッファでのキーマップを変更した際の反映方法が面倒

### 再現手順

1. コンテナに入る

```
cd minimal-dein
docker-compose up -d
docker-compose exec neovim-minimal bash
```

2. nvimを起動

```
cd .config/nvim/
nvim lazy.toml
```

3. 以下の操作によりキーマップを変更→反映
    1. キーマップを変更
    2. 保存して再起動
    3. :DeinUpdateして再起動
    4. 反映完了

反映の確認には `:Denite file/rec` してdeniteバッファを開き `:map` をして確認している

## TOBE
キーマップを変更して再起動するだけで反映させるようにしたい

**Comment by Shougo** [comment]
Please use `dein#load_state()` like this.
No magic.

```vim
if dein#load_state(expand('~/.cache/'))
  call dein#begin(expand('~/.cache/'), [expand('<sfile>', '~/work/lazy.toml')])

  call dein#load_toml('~/work/lazy.toml', {'lazy': 1})

  call dein#end()
  call dein#save_state()
endif
```

**Comment by mikanIchinose** [comment]
load_stateをつけた → 9ae063aed2b46e92d525dcf02cf35183e5f200a9

## 結果

1. キーマップ変更
2. 保存して再起動
3. :DeinUpdateすると反映される

## 次の課題

dein-uiを外して、`:call dein#update()` でいけるかと思ったが無理だった

**Comment by mikanIchinose** [comment]
## 色々試した結果わかったこと

- キーマップ変更→再起動→:DeinUpdate すると変更が反映される
- :call dein#update()を使った場合、どのタイミングで実行しても反映されない
- :call dein#reinstall('denite.nvim')を実行すると反映される
- :call dein#recache_runtimepath()を実行すると反映される
- call dein#recache_runtimepath()をdein#endの直前に配置すると再起動するだけで反映されるようになった

**Comment by mikanIchinose** [comment]
# load_stateを噛ませても再キャッシュされない
## 再現手順

1. コンテナに入る

```
cd minimal-dein
docker-compose up -d
docker-compose exec neovim-minimal bash
```

2. nvimを起動

```
cd .config/nvim/
nvim lazy.toml
```

3. キーマップを`v`から`p`に変更
4. 保存して再起動
5. `:Denite file/rec` → `:map v`, `:map p` でキーマップが変更されているか確認

結果: キーマップが変更されない

↓ vからpに変更しようとしたときに再起動では反映されない様子
![recacheなし](https://user-images.githubusercontent.com/29175998/120208437-6d3c7c80-c268-11eb-8fc8-75d831ecdabc.gif)

## 現状わかっている解決策

- dein#endの直前にdein#recache_runtimepathを配置すると再起動後にキーマップが変更されていることが確認できた

↓ 再起動によりキーマップがvからpに変更される様子
![recacheあり](https://user-images.githubusercontent.com/29175998/120208572-9826d080-c268-11eb-8790-3e275b4d0723.gif)

**Comment by Shougo** [comment]
原因が分かりました。`g:dein#auto_recache` をセットすれば再キャッシュされます。
ftplugin については他の設定と違って `call dein#recache_runtimepath()` でないとキャッシュが作り直されないのが原因です。
ちょっと分かりにく仕様であるので修正を入れました
dein.vim をアップデートしてください。

**Comment by mikanIchinose** [comment]
## dein.vimアプデ後の挙動

```
let g:dein#auto_recache = v:true
```

を仕込むことでftpluginのキーマップ変更が再起動することで反映されるようになった

![auto_recache](https://user-images.githubusercontent.com/29175998/120218312-7f241c80-c274-11eb-94af-bcf880adc368.gif)
